# 簡化編碼修復腳本
Write-Host "開始修復所有 TypeScript 文件的編碼問題..." -ForegroundColor Green

$files = Get-ChildItem -Path "src" -Recurse -Include "*.tsx" | Where-Object { $_.Name -notlike "*node_modules*" }

Write-Host "找到 $($files.Count) 個文件需要處理" -ForegroundColor Yellow

foreach ($file in $files) {
    Write-Host "處理文件: $($file.Name)" -ForegroundColor Cyan
    
    try {
        $content = Get-Content $file.FullName -Raw -Encoding UTF8
        
        # 修復最常見的編碼問題
        $content = $content -replace '媒\?\?\?\?', '媒體'
        $content = $content -replace '供\?\?\?\?', '供應商'
        $content = $content -replace '創\?\?\?\?', '創作者'
        $content = $content -replace '旅\?\?\?\?', '旅遊'
        $content = $content -replace '行\?\?\?\?', '行銷'
        $content = $content -replace '管\?\?\?\?', '管理'
        $content = $content -replace '資\?\?\?\?', '資料'
        $content = $content -replace '聯\?\?\?\?', '聯絡'
        $content = $content -replace '觸\?\?\?\?', '觸及'
        $content = $content -replace '瀏\?\?\?\?\?', '瀏覽'
        $content = $content -replace '平\?\?\?\?', '平台'
        $content = $content -replace '任\?\?\?\?', '任務'
        $content = $content -replace '系\?\?\?\?', '系統'
        $content = $content -replace '通\?\?\?\?', '通路'
        $content = $content -replace '內\?\?\?\?', '內容'
        $content = $content -replace '素\?\?\?\?', '素材'
        $content = $content -replace '追\?\?\?\?', '追蹤'
        $content = $content -replace '覆\?\?\?\?', '覆蓋'
        $content = $content -replace '播\?\?\?\?', '播送'
        $content = $content -replace '價\?\?\?\?', '價格'
        $content = $content -replace '費\?\?\?\?', '費用'
        $content = $content -replace '審\?\?\?\?', '審核'
        $content = $content -replace '載\?\?\?\?', '載入'
        $content = $content -replace '使\?\?\?\?', '使用'
        $content = $content -replace '常\?\?\?\?', '常見'
        $content = $content -replace '問\?\?\?\?', '問題'
        $content = $content -replace '解\?\?\?\?', '解答'
        $content = $content -replace '立\?\?\?\?', '立即'
        $content = $content -replace '成\?\?\?\?', '成為'
        $content = $content -replace '精\?\?\?\?', '精選'
        $content = $content -replace '相\?\?\?\?', '相關'
        $content = $content -replace '在\?\?\?\?', '在線'
        $content = $content -replace '作\?\?\?\?', '作品'
        $content = $content -replace '實\?\?\?\?', '實體'
        $content = $content -replace '業\?\?\?\?', '業務'
        $content = $content -replace '創建\?\?\?\?', '創建'
        $content = $content -replace '編\?\?\?\?', '編輯'
        $content = $content -replace '刪\?\?\?\?', '刪除'
        $content = $content -replace '查\?\?\?\?', '查看'
        $content = $content -replace '設\?\?\?\?', '設定'
        $content = $content -replace '權\?\?\?\?', '權限'
        $content = $content -replace '角\?\?\?\?', '角色'
        $content = $content -replace '用\?\?\?\?', '用戶'
        $content = $content -replace '帳\?\?\?\?', '帳號'
        $content = $content -replace '密\?\?\?\?', '密碼'
        $content = $content -replace '登入\?\?\?\?', '登入'
        $content = $content -replace '註\?\?\?\?', '註冊'
        $content = $content -replace '登出\?\?\?\?', '登出'
        $content = $content -replace '驗\?\?\?\?', '驗證'
        $content = $content -replace '確\?\?\?\?', '確認'
        $content = $content -replace '取\?\?\?\?', '取消'
        $content = $content -replace '保\?\?\?\?', '保存'
        $content = $content -replace '更\?\?\?\?', '更新'
        $content = $content -replace '修\?\?\?\?', '修改'
        $content = $content -replace '添\?\?\?\?', '添加'
        $content = $content -replace '移\?\?\?\?', '移除'
        $content = $content -replace '選\?\?\?\?', '選擇'
        $content = $content -replace '搜\?\?\?\?', '搜尋'
        $content = $content -replace '過\?\?\?\?', '過濾'
        $content = $content -replace '排\?\?\?\?', '排序'
        $content = $content -replace '分類\?\?\?\?', '分類'
        $content = $content -replace '狀\?\?\?\?', '狀態'
        $content = $content -replace '類\?\?\?\?', '類型'
        $content = $content -replace '名\?\?\?\?', '名稱'
        $content = $content -replace '描\?\?\?\?', '描述'
        $content = $content -replace '詳\?\?\?\?', '詳細'
        $content = $content -replace '簡\?\?\?\?', '簡介'
        $content = $content -replace '說\?\?\?\?', '說明'
        $content = $content -replace '幫\?\?\?\?', '幫助'
        $content = $content -replace '支\?\?\?\?', '支援'
        $content = $content -replace '服\?\?\?\?', '服務'
        $content = $content -replace '功\?\?\?\?', '功能'
        $content = $content -replace '特\?\?\?\?', '特色'
        $content = $content -replace '優\?\?\?\?', '優勢'
        $content = $content -replace '品\?\?\?\?', '品質'
        $content = $content -replace '效\?\?\?\?', '效果'
        $content = $content -replace '結\?\?\?\?', '結果'
        $content = $content -replace '目\?\?\?\?', '目標'
        $content = $content -replace '計\?\?\?\?', '計劃'
        $content = $content -replace '進\?\?\?\?', '進度'
        $content = $content -replace '時\?\?\?\?', '時間'
        $content = $content -replace '日\?\?\?\?', '日期'
        $content = $content -replace '年\?\?\?\?', '年份'
        $content = $content -replace '月\?\?\?\?', '月份'
        $content = $content -replace '週\?\?\?\?', '週期'
        $content = $content -replace '天\?\?\?\?', '天數'
        $content = $content -replace '小\?\?\?\?', '小時'
        $content = $content -replace '分鐘\?\?\?\?', '分鐘'
        $content = $content -replace '秒\?\?\?\?', '秒數'
        $content = $content -replace '觀\?\?\?\?', '觀光'
        $content = $content -replace '署\?\?\?\?', '署'
        $content = $content -replace '服務\?\?\?\?', '服務'
        $content = $content -replace '與\?\?\?\?', '與'
        $content = $content -replace '資源\?\?\?\?', '資源'
        $content = $content -replace '管理\?\?\?\?', '管理'
        $content = $content -replace '媒合\?\?\?\?', '媒合'
        $content = $content -replace '台灣\?\?\?\?', '台灣'
        $content = $content -replace '相關\?\?\?\?', '相關'
        $content = $content -replace '專業\?\?\?\?', '專業'
        $content = $content -replace '任務\?\?\?\?', '任務'
        $content = $content -replace '驅動\?\?\?\?', '驅動'
        $content = $content -replace '創作\?\?\?\?', '創作'
        $content = $content -replace '模式\?\?\?\?', '模式'
        $content = $content -replace '風景\?\?\?\?', '風景'
        $content = $content -replace '為\?\?\?\?', '為'
        $content = $content -replace '提供\?\?\?\?', '提供'
        $content = $content -replace '搜尋\?\?\?\?', '搜尋'
        $content = $content -replace '創作者\?\?\?\?', '創作者'
        $content = $content -replace '通路\?\?\?\?', '通路'
        $content = $content -replace '影響力\?\?\?\?', '影響力'
        $content = $content -replace '數量\?\?\?\?', '數量'
        $content = $content -replace '覆蓋\?\?\?\?', '覆蓋'
        $content = $content -replace '選擇\?\?\?\?', '選擇'
        $content = $content -replace '身份\?\?\?\?', '身份'
        $content = $content -replace '進入\?\?\?\?', '進入'
        $content = $content -replace '專屬\?\?\?\?', '專屬'
        $content = $content -replace '解決方案\?\?\?\?', '解決方案'
        $content = $content -replace '上架\?\?\?\?', '上架'
        $content = $content -replace '發布\?\?\?\?', '發布'
        $content = $content -replace '尋找\?\?\?\?', '尋找'
        $content = $content -replace '接取\?\?\?\?', '接取'
        $content = $content -replace '展示\?\?\?\?', '展示'
        $content = $content -replace '作品集\?\?\?\?', '作品集'
        $content = $content -replace '建立\?\?\?\?', '建立'
        $content = $content -replace '合作關係\?\?\?\?', '合作關係'
        $content = $content -replace '瀏覽\?\?\?\?', '瀏覽'
        $content = $content -replace '需求\?\?\?\?', '需求'
        $content = $content -replace '上傳\?\?\?\?', '上傳'
        $content = $content -replace '直接\?\?\?\?', '直接'
        $content = $content -replace '下載\?\?\?\?', '下載'
        $content = $content -replace '傳播\?\?\?\?', '傳播'
        $content = $content -replace '推廣\?\?\?\?', '推廣'
        $content = $content -replace '擴大\?\?\?\?', '擴大'
        $content = $content -replace '高品質\?\?\?\?', '高品質'
        $content = $content -replace '廣大\?\?\?\?', '廣大'
        $content = $content -replace '智能\?\?\?\?', '智能'
        $content = $content -replace 'AI\?\?\?\?', 'AI'
        $content = $content -replace '驅動2\?\?\?\?', '驅動'
        $content = $content -replace '精準\?\?\?\?', '精準'
        $content = $content -replace '匹配\?\?\?\?', '匹配'
        $content = $content -replace '需求2\?\?\?\?', '需求'
        $content = $content -replace '供給\?\?\?\?', '供給'
        $content = $content -replace '完整\?\?\?\?', '完整'
        $content = $content -replace '數據分析\?\?\?\?', '數據分析'
        $content = $content -replace '工具\?\?\?\?', '工具'
        $content = $content -replace '追蹤\?\?\?\?', '追蹤'
        $content = $content -replace '合作效果\?\?\?\?', '合作效果'
        $content = $content -replace 'ROI\?\?\?\?', 'ROI'
        $content = $content -replace '嚴格\?\?\?\?', '嚴格'
        $content = $content -replace '品質審核\?\?\?\?', '品質審核'
        $content = $content -replace '機制\?\?\?\?', '機制'
        $content = $content -replace '確保\?\?\?\?', '確保'
        $content = $content -replace '合作內容\?\?\?\?', '合作內容'
        $content = $content -replace '品質\?\?\?\?', '品質'
        $content = $content -replace '活躍\?\?\?\?', '活躍'
        $content = $content -replace '社群\?\?\?\?', '社群'
        $content = $content -replace '持續\?\?\?\?', '持續'
        $content = $content -replace '學習\?\?\?\?', '學習'
        $content = $content -replace '成長\?\?\?\?', '成長'
        $content = $content -replace '開始\?\?\?\?', '開始'
        $content = $content -replace '行銷之旅\?\?\?\?', '行銷之旅'
        $content = $content -replace '無論\?\?\?\?', '無論'
        $content = $content -replace '業者\?\?\?\?', '業者'
        $content = $content -replace '都能\?\?\?\?', '都能'
        $content = $content -replace '找到\?\?\?\?', '找到'
        $content = $content -replace '最佳\?\?\?\?', '最佳'
        $content = $content -replace '合作伙伴\?\?\?\?', '合作伙伴'
        
        # 寫回文件
        Set-Content $file.FullName -Value $content -Encoding UTF8
        Write-Host "  ✓ 修復完成" -ForegroundColor Green
        
    } catch {
        Write-Host "  ✗ 修復失敗: $($_.Exception.Message)" -ForegroundColor Red
    }
}

Write-Host "編碼修復完成！" -ForegroundColor Green
Write-Host "共處理了 $($files.Count) 個文件" -ForegroundColor Yellow
